apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: nextgen-gitops
  namespace: fleet-default
spec:
  repo: https://github.com/HIRO-MicroDataCenters-BV/ds-gitops.git
  branch: main
  paths:
    - catalog-service/
    - neo4j/
    - search-service/
    - frontend/uva/
    - frontend/ki/
    - frontend/hus/
  targets:
    - clusterName: nextgen