apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: nextgen-gitops
  namespace: fleet-default
spec:
  repo: https://github.com/HIRO-MicroDataCenters-BV/ds-gitops.git
  branch: main
  keepResources: true #resource not removed after gitrepo removal
  correctDrift: #enable self-healing
    enabled: true
  targets:
    - clusterName: nextgen