apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: nextgen
  namespace: fleet-default
spec:
  repo: https://github.com/HIRO-MicroDataCenters-BV/ds-gitops.git
  branch: main
  paths:
    - catalog-service/
    - neo4j/
    - search-service/
  targets:
    - name: nextgen-clusters
      clusterSelector:
        matchLabels:
          name: nextgen