namespace: hus

nodeSelector:
  role: hus

ingress:
  host: ds-policy-engine.hus.nextgen.hiro-develop.nl

cors:
  allowedOrigins: "https://ds-policy-engine-ui.hus.nextgen.hiro-develop.nl"

docs:
  enabled: false

opa:
  enabled: true

persistence:
  enabled: true
  size: 1Gi

env:
  logLevel: INFO
  nodeName: hus
