env:
  - name: DS_SEARCH__PEERS_NAMESPACES
    value: "ki,hus,uva"
  - name: DS_SEARCH__SERVICE_NAME
    value: "ds-search"
  - name: DS_SEARCH__SERVICE_PORT
    value: "8080"
  - name: DS_SEARCH__CATALOG_SERVICE_URL
    value: "http://ds-catalog:8081"
  - name: DS_SEARCH__REQUEST_TIMEOUT
    value: "5.0"
  - name: DS_SEARCH__DISCOVERY_TYPE
    value: "kube"
  - name: LOG_LEVEL
    value: "DEBUG"

ingress:
  host: nextgen.hiro-develop.nl
  

nodeSelector:
  role: ki

namespace: ki