image:
  customImage: "ghcr.io/hiro-microdatacenters-bv/neo4j-semantics:0.1.1-dev.3.develop.4b16ced2"
  pullPolicy: Always
  imagePullSecrets:
    - "docker-image-credentials"

volumes:
  data:
    labels:
      data: "true"
    mode: "defaultStorageClass"
    defaultStorageClass:
      requests:
        storage: 10Gi

neo4j:
  name: my-neo4j-semantics
  password: "123456789"
  acceptLicenseAgreement: "yes"
  edition: enterprise
  config:
    dbms.default_database: "neo4j"
    dbms.security.procedures.unrestricted: "n10s.*,apoc.*"
    dbms.security.procedures.allowlist: "n10s.*,apoc.*"
    dbms.unmanaged_extension_classes: "n10s.endpoint=/rdf"
  startupProbe:
    httpGet:
      path: /
      port: 7474
    initialDelaySeconds: 120
    periodSeconds: 10
    failureThreshold: 30
    timeoutSeconds: 5
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"


nodeSelector: {}

podSpec:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: role
          operator: In
          values:
          - uva